application:
  port: 8080
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
modules:
  web:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: vbridal
      username: web_ue1
      password: yv4wkse5eMYl
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
#    groupMap:
#      order:
#        db:
#          dbName: vbridal
  fdweb:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: vbridal
      username: fd_fdwebrds_ue1
      password: xw4BePCuticz
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5

  ecshop:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: ecshop
      username: fd_erp_ape1
      password: GO8w2dRrHaUI
      config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
      maxOpenConns: 20
      maxIdleConns: 5

  bigdata:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: azkaban
      username: bigdata_ue2
      password: bjQdmVLm732z
      config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
      maxOpenConns: 20
      maxIdleConns: 5

  fdnl:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: vbridal
      username: fd_fdnl_ue1
      password: joigBSfDnx3Y
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
