application:
  port: 8080
modules:
  web:
    db:
      host: master.rds.zone
      port: 3306
      dbName: vbridal
      username: web_ue1
      password: yv4wkse5eMYl
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
#    groupMap:
#      order:
#        db:
#          dbName: vbridal
  fdweb:
    db:
      host: webrds.coeridfqtgzw.us-east-1.rds.amazonaws.com
      port: 3306
      dbName: vbridal
      username: fd_fdwebrds_ue1
      password: xw4BePCuticz
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5

  ecshop:
    db:
      host: web-erp.clzkg2oe0ox1.ap-east-1.rds.amazonaws.com
      port: 3306
      dbName: ecshop
      username: fd_erp_ape1
      password: GO8w2dRrHaUI
      config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
      maxOpenConns: 20
      maxIdleConns: 5

  bigdata:
    db:
      host: fd-bigdata-azkaban-metadata.chynhkcmxjjm.us-east-2.rds.amazonaws.com
      port: 3306
      dbName: azkaban
      username: bigdata_ue2
      password: bjQdmVLm732z
      config: charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
      maxOpenConns: 20
      maxIdleConns: 5

  fdnl:
    db:
      host: webnl.coeridfqtgzw.us-east-1.rds.amazonaws.com
      port: 3306
      dbName: vbridal
      username: fd_fdnl_ue1
      password: joigBSfDnx3Y
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
