application:
  port: 8888
modules:
  web:
    db:
      host: 16.163.46.134
      port: 6033
      dbName: vbridal
      username: web_ue1
      password: yv4wkse5eMYl
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
    groupMap:
      order:
        db:
          dbName: vbridal