application:
  port: 8080
modules:
  web:
    db:
      host: 10.100.4.154
      port: 6033
      dbName: vbridal
      username: web_ue1
      password: yv4wkse5eMYl
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
#    groupMap:
#      order:
#        db:
#          dbName: vbridal
  fdweb:
    db:
      host: 10.100.4.154
      port: 6033
      dbName: vbridal
      username: fd_fdwebrds_ue1
      password: xw4BePCuticz
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5
  ecshop:
    db:
      host: 10.100.4.154
      port: 6033
      dbName: ecshop
      username: erp_ue1
      password: QMcR88cra1jv
      config: charset=utf8mb4&parseTime=True&loc=America%2FLos_Angeles
      maxOpenConns: 20
      maxIdleConns: 5